[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="MilkRunCollection" type="com.mike.website3.dataAnalysis.MilkRunCollection" --]
[#-- @ftlvariable name="ItemCategory" type="com.mike.website3.db.ItemCategory" --]
[#-- @ftlvariable name="MilkRunExtraStop" type="com.mike.website3.db.MilkRunExtraStop" --]
[#-- @ftlvariable name="milkrunUnroutedUI" type="com.mike.website3.milkrun.MilkRunUnroutedUI" file="templates/milkrun-unrouted-by-supplier.ftl" --]
[#-- @ftlvariable name="milkrunDeliveredUI" type="com.mike.website3.milkrun.MilkRunDeliveredUI" file="templates/milkrun-delivered.ftl" --]
[#-- @ftlvariable name="milkrunUnroutedUI" type="com.mike.website3.milkrun.MilkRunUnroutedUI" file="templates/milkrun-unrouted-by-consumer.ftl" --]
[#-- @ftlvariable name="milkrunRoutedUI" type="com.mike.website3.milkrun.MilkRunRoutedUI" file="templates/milkrun-routed.ftl" --]
[#-- @ftlvariable name="milkrunClosedUI" type="com.mike.website3.milkrun.MilkRunUnroutedUI" file="templates/milkrun-unrouted-by-supplier.ftl" --]
[#-- @ftlvariable name="pageState" type="com.mike.website3.pages.internal.RouteAdjusterPageState" file="templates/milkrun-route-adjuster.ftl" --]
[#-- @ftlvariable name="bMilkRun" type="com.mike.website3.milkrun.MilkRunMem" file="templates/milkrun-split-manual-by-eater3.ftl" --]
[#-- @ftlvariable name="aMilkRun" type="com.mike.website3.milkrun.MilkRunMem" file="templates/milkrun-split-manual-by-eater3.ftl" --]
[#-- @ftlvariable name="milkrunDeliveredUI" type="com.mike.website3.milkrun.MilkRunDeliveredUI" file="templates/milkrun-delivering.ftl" --]
[#-- @ftlvariable name="StripeCustomer" type="com.mike.website3.db.Stripe.StripeCustomer.static" --]
[#-- @ftlvariable name="UserRole" type="com.mike.website3.db.UserRole.static" --]
[#-- @ftlvariable name="StandingOrder" type="com.mike.website3.db.StandingOrder.static" --]
[#-- @ftlvariable name="milkrunOpenUI" type="com.mike.website3.milkrun.MilkRunOpenUI.static" --]
[#-- @ftlvariable name="StripeWrapper" type="com.mike.website3.Stripe.StripeWrapper.static" --]
[#-- @ftlvariable name="Participation" type="com.mike.website3.db.Participation.static" --]
[#-- @ftlvariable name="UserNote" type="com.mike.website3.db.UserNote.static" --]
[#-- @ftlvariable name="Address" type="com.mike.website3.db.Address.static" --]
[#-- @ftlvariable name="EmailAddress" type="com.mike.website3.db.EmailAddress.static" --]
[#-- @ftlvariable name="priceData" type="com.mike.website3.pages.external.SeederUpdatePriceUI.static" --]
[#-- @ftlvariable name="ItemAvailability" type="com.mike.website3.db.ItemAvailability.static" --]
[#-- @ftlvariable name="Offer" type="com.mike.website3.db.Offer.static" --]
[#-- @ftlvariable name="Item" type="com.mike.website3.db.Item.static" --]
[#-- @ftlvariable name="User" type="com.mike.website3.db.User.static" --]
[#-- @ftlvariable name="session" type="com.mike.website3.MySessionState" --]
[#-- @ftlvariable name="OfferRoleDB" type="com.mike.website3.db.OfferRoleDB.static" --]
[#-- @ftlvariable name="Rating" type="com.mike.website3.db.Rating.static" --]
[#-- @ftlvariable name="ItemPrice" type="com.mike.website3.db.ItemPrice.static" --]
[#-- @ftlvariable name="String" type="java.lang.String.static" --]
[#-- @ftlvariable name="StripeCharge" type="com.mike.website3.db.Stripe.StripeCharge.static" --]
[#-- @ftlvariable name="MySystemState" type="com.mike.website3.MySystemState.static" --]
[#-- @ftlvariable name="Util" type="com.mike.util.Util.static" --]
[#-- @ftlvariable name="Website" type="com.mike.website3.Website.static" --]
[#-- @ftlvariable name="StringData" type="com.mike.website3.db.StringData.static" --]
[#-- @ftlvariable name="MilkRunDB" type="com.mike.website3.db.MilkRunDB.static" --]
